# General
APPLICATION_NAME = 'oj'  # stands for open journal

# Filenames
CONFIG_FILENAME = f'{APPLICATION_NAME}.ini'

# Mods
DEFAULT = 'DEFAULT'
REWRITE = 'REWRITE'

# Config
## Sections
DEFAULT_SECTION = 'DEFAULT'
PATH_SECTION = 'PATH'
FILENAME_SECTION = 'FILENAME'

## Settings
PATH_SETTINGS = DESTINATION, TEMPLATE = ('destination', 'template')

FILENAME_SETTINGS = DATE_FORMAT, EXTENSION = 'date format', 'extension'

ALL_SETTINGS = PATH_SETTINGS, FILENAME_SETTINGS
