# General
APPLICATION_NAME = 'oj'  # stands for open journal

# Filenames
CONFIG_FILENAME = f'{APPLICATION_NAME}.ini'

# Mods
DEFAULT = 'DEFAULT'

# Config
## Sections
DEFAULT_SECTION = 'DEFAULT'
PATH_SECTION = 'PATH'
FILENAME_SECTION = 'FILENAME'

## Settings
PATH_SETTINGS = DESTINATION, TEMPLATE = ('destination', 'template')

DATE_FORMAT = 'date format'
FILENAME_SETTINGS = (DATE_FORMAT,)

ALL_SETTINGS = PATH_SETTINGS, FILENAME_SETTINGS
